let Kiyimlar=[
    {
        nomi: "Nike brandining malikasi",
        photo:"belarus.jpg",
        category: "futbolka",
        narxi: 120000,
        kiyim_haqida:"Qandaydir malumotlar",
        skidka: true,
    },
    {
        nomi: "Nike brandining krossovkasi",
        photo:"shoe1.webp",
        category: "futbolka",
        narxi: 120000,
        kiyim_haqida: "Qandaydir malumotlar",
        skidka: true,
    },
    {
        nomi: "Nike brandining shortisi",
        photo: "nike.jpg",
        category: "shortik",
        narxi: 100000,
        kiyim_haqida: "Qandaydir malumotlar",
        skidka: false,
    },
    {
        nomi: "Nike brandining krossovkasi",
        photo: "shoe4 (1).webp",
        category: "krossovka",
        narxi: 150000,
        kiyim_haqida: "Qandaydir malumotlar",
        skidka: false,
    },
    {
        nomi: "Nike brandining taqinchog'i",
        photo: "russka.jpg",
        category: "krossovka",
        narxi: 150000,
        kiyim_haqida: "Qandaydir malumotlar",
        skidka: false,
    },
    {
        nomi: "Nike brandining orzulari",
        photo: "orzu.jpg",
        category: "krossovka",
        narxi: false,
        kiyim_haqida: "Qandaydir malumotlar",
        skidka: false,
    },
];